// <auto-generated />
namespace MyStackOverFlow.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _3rdTableCodeAddedInIdentityModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3rdTableCodeAddedInIdentityModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202005030535493_3rdTableCodeAddedInIdentityModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
